name: Compilar Jogo PS2

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Compilar o jogo
    runs-on: ubuntu-24.04
    container:
      image: ps2dev/ps2dev:latest
      options: --user root

    steps:
      - name: Baixar arquivos do projeto
        uses: actions/checkout@v4

      - name: Verificar e compilar
        run: |
          ls -la
          make --version
          make clean
          make

      - name: Salvar arquivo pronto
        uses: actions/upload-artifact@v4
        with:
          name: Panico_na_Floresta
          path: |
            *.elf
            *.irx
            *.o
          retention-days: 30


